# Generated by Django 4.2.7 on 2023-11-13 09:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=25, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('profession', models.CharField(max_length=90)),
                ('what_i_can', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('work_time', models.TimeField(default='00:30', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('city', models.CharField(max_length=150)),
            ],
        ),
    ]
